### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by 1hachem** [gotlougit/midjourney-gallery-downloader#1]
following the readme instructions I get this error

```
Traceback (most recent call last):
  File "/home/hachem/Pictures/ai_generated/midjourney-gallery-downloader/scraper.py", line 37, in <module>
    urllist1 = get_image_urls(url)
  File "/home/hachem/Pictures/ai_generated/midjourney-gallery-downloader/scraper.py", line 18, in get_image_urls
    urllist.append(i.get("event").get("seedImageURL"))
AttributeError: 'str' object has no attribute 'get'
```

**Comment by gotlougit** [comment]
That's interesting, I have not been able to reproduce this error on my machine. Perhaps you have run the script too many times and Cloudflare's rate limiting has kicked in?

Try running `curl -IL midjourney.com/showcase/recents` to see if that is the case?

**Comment by ghost** [comment]
this is the error im getting

F:\#2023\midjourney\midjourney-downloader>python3 scraper.py
Traceback (most recent call last):
  File "F:\#2023\midjourney\midjourney-downloader\scraper.py", line 1, in <module>
    import requests, json, os
ModuleNotFoundError: No module named 'requests'

**Comment by DevGod100** [comment]
Same, need to bypass this...
